# [MANAGER]: Manager Deployment Configurations
controllerManager:
  replicas: 1
  container:
    image:
      repository: packages.broadcom.com/ako/ako-crd-operator
      tag: latest
      imagePullPolicy: IfNotPresent
      pullSecrets: []
    args:
      - "--health-probe-bind-address=:8081"
    resources:
      limits:
        cpu: 256m
        memory: 128Mi
      requests:
        cpu: 128m
        memory: 64Mi
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /readyz
        port: 8081
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10
  serviceAccountName: ako-crd-operator